FROM ruby:3.2

RUN mkdir /data
WORKDIR /data

RUN apt-get update && apt-get install --no-install-recommends -y locales && apt-get clean
RUN curl -fsSL "https://cdn.jsdelivr.net/gh/tj/n/bin/n" | bash -s -- lts

COPY Gemfile Gemfile.lock package.json package-lock.json /data/
COPY _node_module_patch /data/_node_module_patch

RUN gem install bundler && bundle install && npm ci

ENV LANG=C.UTF-8

VOLUME /src
WORKDIR /src
EXPOSE 4000

CMD bundle install && npm ci && bundle exec jekyll serve -H 0.0.0.0
